# Generated by Django 3.1 on 2022-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0003_stock_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
